### ISSUE TITLE
Error with Time Tab

### ISSUE THREAD

**Issue by ghtmtt** [mach0/mutant#10]
Hi Werner,

playing with the plugin (great job)! I get an error in the Time tab due to an API break of `QgsMapLayerRegistry`.

This class does not exist anymore and has been moved to `QgsProject`:

http://qgis.org/api/api_break.html

**Comment by mach0** [comment]
Hi!
I assume you are on the QGIS3.0 version .. 
Thanks for the report - will take a look into it (once I have time - which may take a while ;) )

**Comment by mach0** [comment]
New version to be releases soon.. Error should be gone.
