### ISSUE TITLE
QGIS3 error on startup

### ISSUE THREAD

**Issue by rduivenvoorde** [mach0/mutant#11]
Hi Werner, when I want to enable the plugin on current master I get this error message.

Both on Linux and Windows

![image](https://user-images.githubusercontent.com/731673/31533541-16efd998-aff3-11e7-9089-dfd4394e5ba0.png)

**Comment by pigreco** [comment]
error also in QGIS 3.0.1
![image](https://user-images.githubusercontent.com/7631137/38042742-7c038c36-32b5-11e8-9128-50e6d9bf28d5.png)

**Comment by mach0** [comment]
Hi! While these two errors have nothing to do with each other (first one was fixed) I already know about that - but thanks for reporting it.
I just currently do not have time to fix it (pull requests welcome), thats why the version for QGIS 3.x is still marked as experimental.
Hope I will have time to fix it soon.

**Comment by mach0** [comment]
is this still happening or can this be closed?

**Comment by pigreco** [comment]
@mach0 
wow
it works great
thank you

**Comment by rduivenvoorde** [comment]
Yep, working here. I'll close it.

Thanks!
