### ISSUE TITLE
Error on Enable plugin

### ISSUE THREAD

**Issue by jorgealmerio** [mach0/mutant#12]
As described in api [Backwards Incompatible Changes](https://qgis.org/api/api_break.html) 

> setCrsTransformEnabled(), hasCrsTransformEnabled(), hasCrsTransformEnabledChanged() were removed. CRS transformation is now always enabled.

> Traceback (most recent call last):
			  File "C:/Users/jorgealmerio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\mutant\mutantwidget.py", line 463, in printValue
			    self.iface.mapCanvas().hasCrsTransformEnabled():
			AttributeError: 'QgsMapCanvas' object has no attribute 'hasCrsTransformEnabled'

**Comment by mach0** [comment]
this should be gone with the new version.
Can you confirm?

**Comment by jorgealmerio** [comment]
On enable it's solved, but the problem persists on use the plugin:
             

>  File "C:/Users/jorgealmerio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\mutant\mutantwidget.py", line 487, in printValue
>               self.iface.mapCanvas().hasCrsTransformEnabled():
>              AttributeError: 'QgsMapCanvas' object has no attribute 'hasCrsTransformEnabled'

**Comment by mach0** [comment]
should be solved with the new version.
