### ISSUE TITLE
Mutant is unable to find graphical library

### ISSUE THREAD

**Issue by PooladK** [mach0/mutant#15]
I get an error that the "mutant cannot find any graphic library for creating plots". I do have Qwt, matplitlib and PyQtGraph. I use QGIS 3.6.

**Comment by mach0** [comment]
Just tested it here with Linux debian .. no problem to find the graph libraries (all three)
Do you maybe have those libs for python2 installed where they are needed for python3?

**Comment by PooladK** [comment]
Thanks foe the help. The issue was solved after installation of the libs for pyhton 3.
