### ISSUE TITLE
ERROR PYTHON

### ISSUE THREAD

**Issue by bellanz80** [mach0/mutant#16]
HI. The add-on installs without problems. But, when you activate it and select the layer to see, a python error occurs, and you do not read the pixel information.
Before it worked without problem.
Windows 10 64 bit, QGIS 3.6.
Greetings, thank you very much

![22](https://user-images.githubusercontent.com/38449926/54781070-f237a000-4be0-11e9-8a0d-fef21fee8edf.PNG)

**Comment by mach0** [comment]
do you probably have an exact description (and sample data) to reproduce the problem?
I'd like to rewrite the whole plugin anyway - but currently there is no time for that :(

**Comment by mach0** [comment]
could not reproduce - therefor closed
