### ISSUE TITLE
Coordinate reference system error

### ISSUE THREAD

**Issue by gokulprasad04** [mach0/mutant#20]
![2020-11-18_19-22](https://user-images.githubusercontent.com/72457509/99643413-ee5ebf80-2a4c-11eb-9e63-96f39019e857.png)

When trying to click on the raster to generate a time series graph, it does not do anything and throws out the above error. I could not figure out what was causing this error.

**Comment by mach0** [comment]
Hi and thanks for your report.
May I ask which Coordinate System you are using? And which Coordinate System is assigned to the rasterfile you loaded?

**Comment by gokulprasad04** [comment]
Hi,
Thanks for pointing that out. I didn't realize the project CRS and the raster CRS were not the same. It works now after I changed them.
