### ISSUE TITLE
Use with Web Mapping Service

### ISSUE THREAD

**Issue by psteckman** [mach0/mutant#5]
Hey mach0,

Can this tool work with near real time (NRT) satellite imagery? When I attempt to use it with some NRT raster data, it states that there is, "No valid layers to display."

However, the file I have loaded is a raster file.

Thank you,
Patrick S.

**Comment by mach0** [comment]
Hi!
Honestly I've never loaded a NRT image .. Do you have a sample?
As long as it registers itself as Rasterlayer it should work.. If I get a sample I can take a look why it tells "No valid layers to display".
But I am sure I can make it work with it too.

regards
Werner

**Comment by psteckman** [comment]
Hey,

So, I do have a sample set of data that I can share, but it is just Test Data and it would be best if it was not used for other then being used as sample data.

I will email you the url for the data shortly.

Thank you,
Patrick S.

**Comment by mach0** [comment]
Missed to read the headline .. my bad .. 
So currently it is not possible to use WMS or any webservice to use this plugin with. (Cause it does not really register itself as a Rasterlayer).
Probably I'll have some time next year to investigate, or you'll do a pull request ;)

sorry for that and good luck

**Comment by mach0** [comment]
unlikely to implement remote WMS Servers yet
