### ISSUE TITLE
Set x-axis manually

### ISSUE THREAD

**Issue by mabdelrazek** [mach0/mutant#6]
Hi,
is there a way to set the x-axis manually or at least to limit it? There is a lot of empty space at the begining and the end of the graph and I would like to reduce that.
Thanks!

**Comment by mach0** [comment]
Hi!
I am not sure if I understand what you mean - but for every graphic library I use the standard settings to display them as a Qt-Widget.
Probably there is some setting for each lib to limit it, but I did not take a look into it (patches welcome ;) ).
While there is (currently) no way to adjust the viewed data with matplotlib or Qwt you can zoom in and pan using the PyQtGraph library - maybe that would be enough for your needs.

**Comment by mach0** [comment]
will try to implement QTCharts soon
